import GalleryDetailComponent from "@/components/gallery/ImgDetail";
import Head from "next/head";
import { useRouter } from "next/router";

export default function GalleryDetail() {
  const router = useRouter();
  const id = router.query?.id;

  return (
    <>
      <Head>
        <title>Gallery detail page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {id && <GalleryDetailComponent id={Number(id)} />}
    </>
  );
}
