import ProductDetailComponent from "@/components/shop/ProductDetail";
import Head from "next/head";
import { useRouter } from "next/router";

export default function ShopDetail() {
  const router = useRouter();
  const id = router.query?.id;
  return (
    <>
      <Head>
        <title>Shop detail page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {id && <ProductDetailComponent id={Number(id)} />}
    </>
  );
}
