import NotFound from "@/components/notFound";
import { AuthContext } from "@/context";
import { translate } from "@/utils/functions";
import Head from "next/head";
import { useContext } from "react";

export default function Page404() {
  const { lang } = useContext(AuthContext);
  return (
    <>
      <Head>
        <title>{translate("404.title", lang)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotFound />
    </>
  );
}
