import Head from "next/head";
import Checkout from "@/components/checkout";

export default function CheckoutPage() {
  return (
    <>
      <Head>
        <title>checkout page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Checkout />
    </>
  );
}
