import Head from "next/head";
import ProfilComponent from "@/components/profile";

export default function Profil() {
  return (
    <>
      <Head>
        <title>Profil page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfilComponent />
    </>
  );
}
