import Head from "next/head";
import RegisterPage from "@/components/register";

export default function Register() {
  return (
    <>
      <Head>
        <title>Register page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterPage />
    </>
  );
}
