import IndustryDetailComponent from "@/components/industry/IndustryDetail";
import Head from "next/head";
import { useRouter } from "next/router";

export default function IndustryDetail() {
  const router = useRouter();
  const slug = router.query?.slug;
  return (
    <>
      <Head>
        <title>Industry detail page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {slug && <IndustryDetailComponent slug={String(slug)} />}
    </>
  );
}
