import Head from "next/head";
import IndustryComponent from "@/components/industry";

export default function Industry() {
  return (
    <>
      <Head>
        <title>Industry page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndustryComponent />
    </>
  );
}
